/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.reportes;

/**
 *
 * @author Zacarias
 */
public class MainReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainReportes
     */
    public MainReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tabContenidoReportes = new javax.swing.JTabbedPane();
        panelReportes = new javax.swing.JPanel();
        lbFechaCreacion = new javax.swing.JLabel();
        lbArchivo = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbComentario = new javax.swing.JLabel();
        btGrabarReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        cbTipoRepor = new javax.swing.JComboBox();
        txtFechaCreacion = new javax.swing.JTextField();
        txtArchivo = new javax.swing.JTextField();
        btEliminarReporte = new javax.swing.JButton();
        btEditarReporte = new javax.swing.JButton();
        txtBuscarReporte = new javax.swing.JTextField();
        btBuscarReporte = new javax.swing.JButton();
        btBuscarTodosReporte = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        grReporte = new javax.swing.JTable();
        btDesactivarEditarReporte = new javax.swing.JButton();
        panelInspecciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaInspeccion = new javax.swing.JTextField();
        btInspecciones = new javax.swing.JButton();
        btEliminarInspeccion = new javax.swing.JButton();
        btEditarInspeccion = new javax.swing.JButton();
        txtBuscarInspeccion = new javax.swing.JTextField();
        btBuscarInspeccion = new javax.swing.JButton();
        btBuscarTodosInspeccion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        grInspeccion = new javax.swing.JTable();
        lbIdHabInspeccion = new javax.swing.JLabel();
        lbComentarioInspeccion = new javax.swing.JLabel();
        lbNombreInspector = new javax.swing.JLabel();
        txtComentarioInspeccion = new javax.swing.JTextField();
        txtNombreInspector = new javax.swing.JTextField();
        btDesactivarEditarInspeccion = new javax.swing.JButton();
        cbHabInspeccion = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        lbFechaCreacion.setText("Fecha Creación:");

        lbArchivo.setText("Archivo:");

        lbTipo.setText("Tipo:");

        lbComentario.setText("Comentario:");

        btGrabarReporte.setText("Grabar");

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane1.setViewportView(txtComentario);

        cbTipoRepor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btEliminarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodosReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Fecha Cración", "Archivo", "Tipo", "Comentario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(grReporte);
        if (grReporte.getColumnModel().getColumnCount() > 0) {
            grReporte.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btDesactivarEditarReporte.setText("Salir Modo Editar");

        javax.swing.GroupLayout panelReportesLayout = new javax.swing.GroupLayout(panelReportes);
        panelReportes.setLayout(panelReportesLayout);
        panelReportesLayout.setHorizontalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReportesLayout.createSequentialGroup()
                        .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(panelReportesLayout.createSequentialGroup()
                                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelReportesLayout.createSequentialGroup()
                                        .addComponent(btEliminarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btEditarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBuscarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btBuscarReporte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btBuscarTodosReporte))
                                    .addComponent(lbArchivo)
                                    .addComponent(lbTipo)
                                    .addComponent(lbComentario)
                                    .addComponent(btGrabarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelReportesLayout.createSequentialGroup()
                        .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReportesLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipoRepor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelReportesLayout.createSequentialGroup()
                                .addComponent(lbFechaCreacion)
                                .addGap(31, 31, 31)
                                .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesactivarEditarReporte)
                        .addGap(41, 41, 41))))
        );
        panelReportesLayout.setVerticalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarReporte)
                    .addComponent(btEditarReporte)
                    .addComponent(txtBuscarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarReporte)
                    .addComponent(btBuscarTodosReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaCreacion)
                    .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarReporte))
                .addGap(18, 18, 18)
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbArchivo)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTipo)
                    .addComponent(cbTipoRepor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbComentario)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGrabarReporte)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tabContenidoReportes.addTab("Reportes", panelReportes);

        jLabel1.setText("Fecha Inspección:");

        btInspecciones.setText("Grabar");

        btEliminarInspeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarInspeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarInspeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodosInspeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grInspeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Habitación Inspección", "Fecha Inspección", "Comentario", "Nombre Inspector"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(grInspeccion);
        if (grInspeccion.getColumnModel().getColumnCount() > 0) {
            grInspeccion.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        lbIdHabInspeccion.setText("Habitación Inspección:");

        lbComentarioInspeccion.setText("Comentario:");

        lbNombreInspector.setText("Nombre Inspector:");

        btDesactivarEditarInspeccion.setText("Salir Modo Editar");

        cbHabInspeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelInspeccionesLayout = new javax.swing.GroupLayout(panelInspecciones);
        panelInspecciones.setLayout(panelInspeccionesLayout);
        panelInspeccionesLayout.setHorizontalGroup(
            panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInspeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInspeccionesLayout.createSequentialGroup()
                        .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInspeccionesLayout.createSequentialGroup()
                                .addComponent(btEliminarInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditarInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarInspeccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscarTodosInspeccion))
                            .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btInspecciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInspeccionesLayout.createSequentialGroup()
                                    .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(lbComentarioInspeccion)
                                        .addComponent(lbNombreInspector))
                                    .addGap(35, 35, 35)
                                    .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFechaInspeccion, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(txtComentarioInspeccion)
                                        .addComponent(txtNombreInspector)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInspeccionesLayout.createSequentialGroup()
                        .addComponent(lbIdHabInspeccion)
                        .addGap(18, 18, 18)
                        .addComponent(cbHabInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesactivarEditarInspeccion)
                        .addGap(49, 49, 49))))
        );
        panelInspeccionesLayout.setVerticalGroup(
            panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInspeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarInspeccion)
                    .addComponent(btEditarInspeccion)
                    .addComponent(txtBuscarInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarInspeccion)
                    .addComponent(btBuscarTodosInspeccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdHabInspeccion)
                    .addComponent(btDesactivarEditarInspeccion)
                    .addComponent(cbHabInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInspeccionesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbComentarioInspeccion)
                        .addGap(18, 18, 18)
                        .addGroup(panelInspeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombreInspector)
                            .addComponent(txtNombreInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInspeccionesLayout.createSequentialGroup()
                        .addComponent(txtFechaInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtComentarioInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btInspecciones)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        tabContenidoReportes.addTab("Inspecciones Sanitarias", panelInspecciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenidoReportes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenidoReportes)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarInspeccion;
    private javax.swing.JButton btBuscarReporte;
    private javax.swing.JButton btBuscarTodosInspeccion;
    private javax.swing.JButton btBuscarTodosReporte;
    private javax.swing.JButton btDesactivarEditarInspeccion;
    private javax.swing.JButton btDesactivarEditarReporte;
    private javax.swing.JButton btEditarInspeccion;
    private javax.swing.JButton btEditarReporte;
    private javax.swing.JButton btEliminarInspeccion;
    private javax.swing.JButton btEliminarReporte;
    private javax.swing.JButton btGrabarReporte;
    private javax.swing.JButton btInspecciones;
    private javax.swing.JComboBox<String> cbHabInspeccion;
    private javax.swing.JComboBox cbTipoRepor;
    private javax.swing.JTable grInspeccion;
    private javax.swing.JTable grReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbArchivo;
    private javax.swing.JLabel lbComentario;
    private javax.swing.JLabel lbComentarioInspeccion;
    private javax.swing.JLabel lbFechaCreacion;
    private javax.swing.JLabel lbIdHabInspeccion;
    private javax.swing.JLabel lbNombreInspector;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JPanel panelInspecciones;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JTabbedPane tabContenidoReportes;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtBuscarInspeccion;
    private javax.swing.JTextField txtBuscarReporte;
    private javax.swing.JTextArea txtComentario;
    private javax.swing.JTextField txtComentarioInspeccion;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtFechaInspeccion;
    private javax.swing.JTextField txtNombreInspector;
    // End of variables declaration//GEN-END:variables
}
