/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.localizador;

/**
 *
 * @author Zacarias
 */
public class MainLocalizador extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainLocalizador
     */
    public MainLocalizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tabContLocalizador = new javax.swing.JTabbedPane();
        panelPais = new javax.swing.JPanel();
        lbNombreRegion = new javax.swing.JLabel();
        btGrabarRegion = new javax.swing.JButton();
        txtNombreRegion = new javax.swing.JTextField();
        panelProvincia = new javax.swing.JPanel();
        lbNombreProvincia = new javax.swing.JLabel();
        lbPaisP = new javax.swing.JLabel();
        btGrabarProvincia = new javax.swing.JButton();
        txtNombreProvincia = new javax.swing.JTextField();
        cbPaisP = new javax.swing.JComboBox();
        panelComuna = new javax.swing.JPanel();
        lbNombreComuna = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbProvinciaC = new javax.swing.JLabel();
        lbPaisC = new javax.swing.JLabel();
        btGrabarComuna = new javax.swing.JButton();
        cbProvinciaC = new javax.swing.JComboBox();
        cbPaisC = new javax.swing.JComboBox();
        panelBuscarLocalizador = new javax.swing.JPanel();
        lbNombreBuscar = new javax.swing.JLabel();
        txtNombreBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btBuscarLocalizador = new javax.swing.JButton();

        jButton1.setText("jButton1");

        lbNombreRegion.setText("Nombre Region:");

        btGrabarRegion.setText("Grabar");

        javax.swing.GroupLayout panelPaisLayout = new javax.swing.GroupLayout(panelPais);
        panelPais.setLayout(panelPaisLayout);
        panelPaisLayout.setHorizontalGroup(
            panelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaisLayout.createSequentialGroup()
                .addGroup(panelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPaisLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbNombreRegion)
                        .addGap(31, 31, 31)
                        .addComponent(txtNombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPaisLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btGrabarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelPaisLayout.setVerticalGroup(
            panelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaisLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreRegion)
                    .addComponent(txtNombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btGrabarRegion)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        tabContLocalizador.addTab("Region", panelPais);

        lbNombreProvincia.setText("Nombre Provincia:");

        lbPaisP.setText("País");

        btGrabarProvincia.setText("Grabar");

        cbPaisP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelProvinciaLayout = new javax.swing.GroupLayout(panelProvincia);
        panelProvincia.setLayout(panelProvinciaLayout);
        panelProvinciaLayout.setHorizontalGroup(
            panelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProvinciaLayout.createSequentialGroup()
                .addGroup(panelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProvinciaLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(panelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreProvincia)
                            .addComponent(lbPaisP))
                        .addGap(43, 43, 43)
                        .addGroup(panelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPaisP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelProvinciaLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btGrabarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        panelProvinciaLayout.setVerticalGroup(
            panelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProvinciaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreProvincia)
                    .addComponent(txtNombreProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPaisP)
                    .addComponent(cbPaisP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btGrabarProvincia)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        tabContLocalizador.addTab("Provincia", panelProvincia);

        lbNombreComuna.setText("Nombre Comuna:");

        lbProvinciaC.setText("Provincia:");

        lbPaisC.setText("País:");

        btGrabarComuna.setText("Grabar");

        cbProvinciaC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbPaisC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelComunaLayout = new javax.swing.GroupLayout(panelComuna);
        panelComuna.setLayout(panelComunaLayout);
        panelComunaLayout.setHorizontalGroup(
            panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComunaLayout.createSequentialGroup()
                .addGroup(panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComunaLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNombreComuna)
                            .addComponent(lbProvinciaC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPaisC, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(49, 49, 49)
                        .addGroup(panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbProvinciaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPaisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelComunaLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btGrabarComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelComunaLayout.setVerticalGroup(
            panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComunaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreComuna)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProvinciaC)
                    .addComponent(cbProvinciaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelComunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPaisC)
                    .addComponent(cbPaisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btGrabarComuna)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tabContLocalizador.addTab("Comuna", panelComuna);

        lbNombreBuscar.setText("Nombre:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btBuscarLocalizador.setText("Buscar");

        javax.swing.GroupLayout panelBuscarLocalizadorLayout = new javax.swing.GroupLayout(panelBuscarLocalizador);
        panelBuscarLocalizador.setLayout(panelBuscarLocalizadorLayout);
        panelBuscarLocalizadorLayout.setHorizontalGroup(
            panelBuscarLocalizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLocalizadorLayout.createSequentialGroup()
                .addGroup(panelBuscarLocalizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLocalizadorLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lbNombreBuscar)
                        .addGap(38, 38, 38)
                        .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btBuscarLocalizador))
                    .addGroup(panelBuscarLocalizadorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelBuscarLocalizadorLayout.setVerticalGroup(
            panelBuscarLocalizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLocalizadorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelBuscarLocalizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreBuscar)
                    .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarLocalizador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tabContLocalizador.addTab("Buscar", panelBuscarLocalizador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContLocalizador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContLocalizador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarLocalizador;
    private javax.swing.JButton btGrabarComuna;
    private javax.swing.JButton btGrabarProvincia;
    private javax.swing.JButton btGrabarRegion;
    private javax.swing.JComboBox cbPaisC;
    private javax.swing.JComboBox cbPaisP;
    private javax.swing.JComboBox cbProvinciaC;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbNombreBuscar;
    private javax.swing.JLabel lbNombreComuna;
    private javax.swing.JLabel lbNombreProvincia;
    private javax.swing.JLabel lbNombreRegion;
    private javax.swing.JLabel lbPaisC;
    private javax.swing.JLabel lbPaisP;
    private javax.swing.JLabel lbProvinciaC;
    private javax.swing.JPanel panelBuscarLocalizador;
    private javax.swing.JPanel panelComuna;
    private javax.swing.JPanel panelPais;
    private javax.swing.JPanel panelProvincia;
    private javax.swing.JTabbedPane tabContLocalizador;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtNombreProvincia;
    private javax.swing.JTextField txtNombreRegion;
    // End of variables declaration//GEN-END:variables
}
