    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.localizador;


/**
 *
 * @author Zacarias
 */
public class MainLocalizador extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainLocalizador
     */
    public MainLocalizador() {
        initComponents();
        tabContLocalizador.addTab("Regiones", new panelRegion());
        tabContLocalizador.addTab("Provincias", new panelProvincias());
        tabContLocalizador.addTab("Comunas", new panelComunas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tabContLocalizador = new javax.swing.JTabbedPane();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContLocalizador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContLocalizador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane tabContLocalizador;
    // End of variables declaration//GEN-END:variables
}
