/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.insumos;

import helper.Formularios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veranum.DAO.DAOInsumos;
import veranum.entities.ClInsumos;

/**
 *
 * @author Zacarias
 */
public class MainInsumos extends javax.swing.JInternalFrame {

    private boolean paraGrabar = false;
    private DefaultTableModel dt = new DefaultTableModel();
    private int id = 0;
    
    /**
     * Creates new form MainInsumos
     */
    public MainInsumos() {
        initComponents();
        grInsumos.setEnabled(true);
        Formularios.DesactiveBotonesEliminarEditar(btEditarInsumos, btEditarInsumos);
        btDesactivarEditarInsumos.setVisible(false);
        this.leerTodos(true);
        tabContenidoInsumos.addTab("TipoMenu", new panelTipoMenu());
    }
    
     // Method Custom
    private void leerInsumos(int id){
        this.id = id;
        ClInsumos ins = DAOInsumos.sqlLeer(id);
        txtNombreInsumos.setText(ins.getNombre());
        txtDescripcionInsumos.setText(ins.getDescripcion());
    }
    
    private void leerTodos(boolean todos){
        ArrayList ins = new ArrayList<>();
        if(todos)
            ins = DAOInsumos.sqlLeerTodos();
        else 
            ins = DAOInsumos.sqlBuscarByNombre(txtBuscarInsumos.getText());
        
        dt =  (DefaultTableModel) grInsumos.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }        
        for(int x=0; x < ins.size(); x++){
            ClInsumos xx = (ClInsumos)ins.get(x);
            Object[] fila = new Object[7];
            fila[0] = xx.getIdInsumo();
            fila[1] = xx.getNombre();
            fila[2] = xx.getDescripcion(); 
            dt.addRow(fila);
        }
    }
    
    private void btnEditarMode(){
        if(!this.paraGrabar){
            btDesactivarEditarInsumos.setVisible(false);
            helper.Formularios.limpiar(panelInsumos);
        } else {
            btDesactivarEditarInsumos.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContenidoInsumos = new javax.swing.JTabbedPane();
        panelInsumos = new javax.swing.JPanel();
        lbNombreInsumo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreInsumos = new javax.swing.JTextField();
        txtDescripcionInsumos = new javax.swing.JTextField();
        btGrabarInsumos = new javax.swing.JButton();
        btEliminarInsumos = new javax.swing.JButton();
        btEditarInsumos = new javax.swing.JButton();
        txtBuscarInsumos = new javax.swing.JTextField();
        btBuscarInsumos = new javax.swing.JButton();
        btBuscarTodosInsumos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        grInsumos = new javax.swing.JTable();
        btDesactivarEditarInsumos = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        lbNombreMenu = new javax.swing.JLabel();
        btGrabarMenu = new javax.swing.JButton();
        txtNombreMenu = new javax.swing.JTextField();
        lbTipoMenu = new javax.swing.JLabel();
        cbTipoMenu = new javax.swing.JComboBox();
        btEliminarMenu = new javax.swing.JButton();
        btEditarMenu = new javax.swing.JButton();
        txtBuscarMenu = new javax.swing.JTextField();
        btBuscarMenu = new javax.swing.JButton();
        btBuscarTodosMenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        grMenu = new javax.swing.JTable();
        btDesactivarEditarMenu = new javax.swing.JButton();
        panelMedidas = new javax.swing.JPanel();
        btEliminarMedida = new javax.swing.JButton();
        btEditarMedida = new javax.swing.JButton();
        txtBuscarMedida = new javax.swing.JTextField();
        btBuscarMedida = new javax.swing.JButton();
        btBuscarTodosMedida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grMedida = new javax.swing.JTable();
        lbNombreMedida = new javax.swing.JLabel();
        txtNombreMedida = new javax.swing.JTextField();
        btGrabarMedida = new javax.swing.JButton();
        btDesactivarEditarMedida = new javax.swing.JButton();

        lbNombreInsumo.setText("Nombre Insumo:");

        jLabel2.setText("Descripción:");

        btGrabarInsumos.setText("Grabar");
        btGrabarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrabarInsumosActionPerformed(evt);
            }
        });

        btEliminarInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N
        btEliminarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarInsumosActionPerformed(evt);
            }
        });

        btEditarInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N
        btEditarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarInsumosActionPerformed(evt);
            }
        });

        btBuscarInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N
        btBuscarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarInsumosActionPerformed(evt);
            }
        });

        btBuscarTodosInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N
        btBuscarTodosInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTodosInsumosActionPerformed(evt);
            }
        });

        grInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Nombre Insumo", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grInsumosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(grInsumos);
        if (grInsumos.getColumnModel().getColumnCount() > 0) {
            grInsumos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btDesactivarEditarInsumos.setText("Salir Modo Editar");
        btDesactivarEditarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesactivarEditarInsumosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInsumosLayout = new javax.swing.GroupLayout(panelInsumos);
        panelInsumos.setLayout(panelInsumosLayout);
        panelInsumosLayout.setHorizontalGroup(
            panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInsumosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(panelInsumosLayout.createSequentialGroup()
                        .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btGrabarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInsumosLayout.createSequentialGroup()
                                .addComponent(btEliminarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btBuscarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarTodosInsumos))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInsumosLayout.createSequentialGroup()
                        .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescripcionInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInsumosLayout.createSequentialGroup()
                                .addComponent(lbNombreInsumo)
                                .addGap(27, 27, 27)
                                .addComponent(txtNombreInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesactivarEditarInsumos)
                        .addGap(46, 46, 46))))
        );
        panelInsumosLayout.setVerticalGroup(
            panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBuscarInsumos)
                    .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btEliminarInsumos)
                        .addComponent(btEditarInsumos)
                        .addComponent(txtBuscarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBuscarTodosInsumos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreInsumo)
                    .addComponent(txtNombreInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarInsumos))
                .addGap(18, 18, 18)
                .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcionInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGrabarInsumos)
                .addGap(210, 210, 210))
        );

        tabContenidoInsumos.addTab("Insumos", panelInsumos);

        lbNombreMenu.setText("Nombre menú:");

        btGrabarMenu.setText("Grabar");

        lbTipoMenu.setText("Tipo Menú:");

        cbTipoMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btEliminarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Tipo Menú", "Nombre Menú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(grMenu);
        if (grMenu.getColumnModel().getColumnCount() > 0) {
            grMenu.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btDesactivarEditarMenu.setText("Salir Modo Editar");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipoMenu)
                            .addComponent(lbNombreMenu))
                        .addGap(27, 27, 27)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addComponent(txtNombreMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(224, Short.MAX_VALUE))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addComponent(cbTipoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDesactivarEditarMenu)
                                .addGap(108, 108, 108))))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMenuLayout.createSequentialGroup()
                                        .addComponent(btEliminarMenu)
                                        .addGap(18, 18, 18)
                                        .addComponent(btEditarMenu)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBuscarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btBuscarMenu)
                                        .addGap(18, 18, 18)
                                        .addComponent(btBuscarTodosMenu))
                                    .addComponent(btGrabarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarMenu)
                    .addComponent(btEditarMenu)
                    .addComponent(txtBuscarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarMenu)
                    .addComponent(btBuscarTodosMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTipoMenu)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTipoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btDesactivarEditarMenu)))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreMenu)
                    .addComponent(txtNombreMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btGrabarMenu)
                .addGap(242, 242, 242))
        );

        tabContenidoInsumos.addTab("Menú", panelMenu);

        btEliminarMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodosMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Nombre Medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grMedida);

        lbNombreMedida.setText("Nombre Medida");

        btGrabarMedida.setText("Grabar");

        btDesactivarEditarMedida.setText("Salir Modo Editar");

        javax.swing.GroupLayout panelMedidasLayout = new javax.swing.GroupLayout(panelMedidas);
        panelMedidas.setLayout(panelMedidasLayout);
        panelMedidasLayout.setHorizontalGroup(
            panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedidasLayout.createSequentialGroup()
                        .addGroup(panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panelMedidasLayout.createSequentialGroup()
                                .addComponent(btEliminarMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditarMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarMedida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscarTodosMedida)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelMedidasLayout.createSequentialGroup()
                        .addGroup(panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btGrabarMedida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMedidasLayout.createSequentialGroup()
                                .addComponent(lbNombreMedida)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btDesactivarEditarMedida)
                        .addGap(111, 111, 111))))
        );
        panelMedidasLayout.setVerticalGroup(
            panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarMedida)
                    .addComponent(btEditarMedida)
                    .addComponent(txtBuscarMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarMedida)
                    .addComponent(btBuscarTodosMedida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreMedida)
                    .addComponent(txtNombreMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarMedida))
                .addGap(18, 18, 18)
                .addComponent(btGrabarMedida)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        tabContenidoInsumos.addTab("Medidas", panelMedidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenidoInsumos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenidoInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEliminarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarInsumosActionPerformed
        this.leerInsumos(Formularios.getSelectedRow(grInsumos));
        if(this.id == 0){
            JOptionPane.showMessageDialog(this, "NO existe para eliminar");
        }else{
            DAOInsumos.sqlDelete(new ClInsumos(this.id));
            JOptionPane.showMessageDialog(this, "Eliminado");
            helper.Formularios.limpiar(panelInsumos);
            Formularios.DesactiveBotonesEliminarEditar(btEditarInsumos, btEliminarInsumos);
            this.leerTodos(true);
        }
    }//GEN-LAST:event_btEliminarInsumosActionPerformed

    private void btEditarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarInsumosActionPerformed
        this.leerInsumos(Formularios.getSelectedRow(grInsumos));
        this.paraGrabar = true;
        this.btnEditarMode();
    }//GEN-LAST:event_btEditarInsumosActionPerformed

    private void btBuscarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarInsumosActionPerformed
        this.leerTodos(false);
    }//GEN-LAST:event_btBuscarInsumosActionPerformed

    private void btBuscarTodosInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTodosInsumosActionPerformed
        this.leerTodos(true);
    }//GEN-LAST:event_btBuscarTodosInsumosActionPerformed

    private void btDesactivarEditarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesactivarEditarInsumosActionPerformed
        this.paraGrabar = false;
        this.btnEditarMode();
    }//GEN-LAST:event_btDesactivarEditarInsumosActionPerformed

    private void btGrabarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrabarInsumosActionPerformed
        if(!paraGrabar){
            if(txtNombreInsumos.getText().equals("") || txtDescripcionInsumos.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Ingrese los Datos");
            }else{
            DAOInsumos.sqlInsert(new ClInsumos(txtNombreInsumos.getText()
                                                   , txtDescripcionInsumos.getText())
                                );
            JOptionPane.showMessageDialog(this, "Agregado");
            Formularios.DesactiveBotonesEliminarEditar(btEditarInsumos, btEliminarInsumos);
            helper.Formularios.limpiar(panelInsumos);
            this.leerTodos(true);
        }  
        }else{
            DAOInsumos.sqlUpdate(     new ClInsumos(this.id, txtNombreInsumos.getText()
                                        , txtDescripcionInsumos.getText()));
            JOptionPane.showMessageDialog(this, "Modificado");
            Formularios.DesactiveBotonesEliminarEditar(btEditarInsumos, btEliminarInsumos);
            helper.Formularios.limpiar(panelInsumos);
            this.leerTodos(true);
        }
    }//GEN-LAST:event_btGrabarInsumosActionPerformed

    private void grInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grInsumosMouseClicked
        int row_dos = Formularios.getTablaSeleccionada(evt, grInsumos, 2);
        
        if(row_dos >= 0){
            this.leerInsumos(Integer.parseInt(grInsumos.getValueAt(row_dos, 0).toString()));
            Formularios.ActiveBotonesEliminarEditar(btEditarInsumos, btEliminarInsumos);
            this.paraGrabar = true;
            this.btnEditarMode();
        } else {
            Formularios.ActiveBotonesEliminarEditar(btEditarInsumos, btEliminarInsumos);
        }
    }//GEN-LAST:event_grInsumosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarInsumos;
    private javax.swing.JButton btBuscarMedida;
    private javax.swing.JButton btBuscarMenu;
    private javax.swing.JButton btBuscarTodosInsumos;
    private javax.swing.JButton btBuscarTodosMedida;
    private javax.swing.JButton btBuscarTodosMenu;
    private javax.swing.JButton btDesactivarEditarInsumos;
    private javax.swing.JButton btDesactivarEditarMedida;
    private javax.swing.JButton btDesactivarEditarMenu;
    private javax.swing.JButton btEditarInsumos;
    private javax.swing.JButton btEditarMedida;
    private javax.swing.JButton btEditarMenu;
    private javax.swing.JButton btEliminarInsumos;
    private javax.swing.JButton btEliminarMedida;
    private javax.swing.JButton btEliminarMenu;
    private javax.swing.JButton btGrabarInsumos;
    private javax.swing.JButton btGrabarMedida;
    private javax.swing.JButton btGrabarMenu;
    private javax.swing.JComboBox cbTipoMenu;
    private javax.swing.JTable grInsumos;
    private javax.swing.JTable grMedida;
    private javax.swing.JTable grMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbNombreInsumo;
    private javax.swing.JLabel lbNombreMedida;
    private javax.swing.JLabel lbNombreMenu;
    private javax.swing.JLabel lbTipoMenu;
    private javax.swing.JPanel panelInsumos;
    private javax.swing.JPanel panelMedidas;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTabbedPane tabContenidoInsumos;
    private javax.swing.JTextField txtBuscarInsumos;
    private javax.swing.JTextField txtBuscarMedida;
    private javax.swing.JTextField txtBuscarMenu;
    private javax.swing.JTextField txtDescripcionInsumos;
    private javax.swing.JTextField txtNombreInsumos;
    private javax.swing.JTextField txtNombreMedida;
    private javax.swing.JTextField txtNombreMenu;
    // End of variables declaration//GEN-END:variables
}
