/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.servicios;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veranum.DAO.DAOServicios;
import veranum.entities.ClServicios;

/**
 *
 * @author Duoc
 */
public class MainServicios extends javax.swing.JInternalFrame {

    private boolean paraGrabar = false;
    private DefaultTableModel dt = new DefaultTableModel();
    /**
     * Creates new form MainServicios
     */
    public MainServicios() {
        initComponents();
        grServicio.setEnabled(false);
        btEliminar.setEnabled(false);
    }
    
    private void leerTodos(){
        ArrayList ser = DAOServicios.sqlLeerTodos();
        dt =  (DefaultTableModel) grServicio.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }        
        for(int x=0; x < ser.size(); x++){
            ClServicios xx = (ClServicios)ser.get(x);
            Object[] fila = new Object[7];
            fila[2] = xx.getIdServicio();
            fila[0] = xx.getNombre();
            fila[1] = xx.getPrecio(); 
            dt.addRow(fila);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContServicios = new javax.swing.JTabbedPane();
        panelServicios = new javax.swing.JPanel();
        lbNombreServicio = new javax.swing.JLabel();
        lbPrecioServicio = new javax.swing.JLabel();
        txtNombreServicio = new javax.swing.JTextField();
        txtPrecioServicio = new javax.swing.JTextField();
        btGrabarServicio = new javax.swing.JButton();
        btBuscarServicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grServicio = new javax.swing.JTable();
        btBuscarTodosSer = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        panelCentroEventos = new javax.swing.JPanel();
        lbHotelCentroEvento = new javax.swing.JLabel();
        txtHotelCentroEvento = new javax.swing.JTextField();
        lbPrecioCentroEvento = new javax.swing.JLabel();
        txtPrecioCentroEvento = new javax.swing.JTextField();
        lbCaracCentroEvento = new javax.swing.JLabel();
        txtCaracCentroEvento = new javax.swing.JTextField();
        btGrabarCentroEvento = new javax.swing.JButton();
        lbDisponibleCentroEvento = new javax.swing.JLabel();
        cbDisponibleCentroEvento = new javax.swing.JComboBox();

        lbNombreServicio.setText("Nombre Servicio:");

        lbPrecioServicio.setText("Precio:");

        btGrabarServicio.setText("Grabar");
        btGrabarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrabarServicioActionPerformed(evt);
            }
        });

        btBuscarServicio.setText("Buscar");
        btBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarServicioActionPerformed(evt);
            }
        });

        grServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(grServicio);

        btBuscarTodosSer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N
        btBuscarTodosSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTodosSerActionPerformed(evt);
            }
        });

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelServiciosLayout = new javax.swing.GroupLayout(panelServicios);
        panelServicios.setLayout(panelServiciosLayout);
        panelServiciosLayout.setHorizontalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiciosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addGroup(panelServiciosLayout.createSequentialGroup()
                        .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btGrabarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelServiciosLayout.createSequentialGroup()
                                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombreServicio)
                                    .addComponent(lbPrecioServicio))
                                .addGap(18, 18, 18)
                                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(txtPrecioServicio))))
                        .addGap(34, 34, 34)
                        .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBuscarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btBuscarTodosSer))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelServiciosLayout.setVerticalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServiciosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreServicio)
                    .addComponent(txtNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecioServicio)
                    .addComponent(txtPrecioServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminar))
                .addGap(27, 27, 27)
                .addComponent(btGrabarServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarTodosSer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabContServicios.addTab("Servicios Extras", panelServicios);

        lbHotelCentroEvento.setText("Hotel:");

        lbPrecioCentroEvento.setText("Precio:");

        lbCaracCentroEvento.setText("Caracteristicas:");

        btGrabarCentroEvento.setText("Grabar");

        lbDisponibleCentroEvento.setText("Disponible:");

        cbDisponibleCentroEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelCentroEventosLayout = new javax.swing.GroupLayout(panelCentroEventos);
        panelCentroEventos.setLayout(panelCentroEventosLayout);
        panelCentroEventosLayout.setHorizontalGroup(
            panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroEventosLayout.createSequentialGroup()
                .addGroup(panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentroEventosLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHotelCentroEvento)
                            .addComponent(lbPrecioCentroEvento)
                            .addComponent(lbCaracCentroEvento)
                            .addComponent(lbDisponibleCentroEvento))
                        .addGap(78, 78, 78)
                        .addGroup(panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbDisponibleCentroEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHotelCentroEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtPrecioCentroEvento)
                            .addComponent(txtCaracCentroEvento)))
                    .addGroup(panelCentroEventosLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btGrabarCentroEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        panelCentroEventosLayout.setVerticalGroup(
            panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentroEventosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHotelCentroEvento)
                    .addComponent(txtHotelCentroEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecioCentroEvento)
                    .addComponent(txtPrecioCentroEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCaracCentroEvento)
                    .addComponent(txtCaracCentroEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelCentroEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisponibleCentroEvento)
                    .addComponent(cbDisponibleCentroEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGrabarCentroEvento)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        tabContServicios.addTab("Centro de Eventos", panelCentroEventos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContServicios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContServicios)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGrabarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrabarServicioActionPerformed
        if(!paraGrabar){
            if(txtNombreServicio.getText().equals("") || txtPrecioServicio.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Ingrese los Datos");
            }else{
            DAOServicios.sqlInsert(new ClServicios(txtNombreServicio.getText()
                                                   , Integer.parseInt(txtPrecioServicio.getText()))
                                );
            JOptionPane.showMessageDialog(this, "Agregado");
            btEliminar.setEnabled(false);
            helper.Formularios.limpiar(panelServicios);
        }  
        }else{
            DAOServicios.sqlUpdate(new ClServicios(txtNombreServicio.getText()
                                           , Integer.parseInt(txtPrecioServicio.getText()) )
                );
            JOptionPane.showMessageDialog(this, "Modificado");
            btEliminar.setEnabled(false);
            helper.Formularios.limpiar(panelServicios);
        }      
    }//GEN-LAST:event_btGrabarServicioActionPerformed
        
    private void btBuscarTodosSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTodosSerActionPerformed
        this.leerTodos();
    }//GEN-LAST:event_btBuscarTodosSerActionPerformed

    private void btBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarServicioActionPerformed
        ClServicios servicio = DAOServicios.sqlLeer(txtNombreServicio.getText());
        if(servicio!=null){
            txtNombreServicio.setText(servicio.getNombre());
            txtPrecioServicio.setText(String.valueOf(servicio.getPrecio()));
            btEliminar.setEnabled(true);
            paraGrabar = true;
        }else {
            JOptionPane.showMessageDialog(this, "no existe!");
            btEliminar.setEnabled(false);
            paraGrabar = false;
        }
    }//GEN-LAST:event_btBuscarServicioActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        if(!paraGrabar){
            JOptionPane.showMessageDialog(this, "NO existe para eliminar");
        }else{
            DAOServicios.sqlDelete(new ClServicios(txtNombreServicio.getText()));
            JOptionPane.showMessageDialog(this, "Eliminado");
            helper.Formularios.limpiar(panelServicios);
            btEliminar.setEnabled(false);
            //paraGrabar = true;
        }
    }//GEN-LAST:event_btEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarServicio;
    private javax.swing.JButton btBuscarTodosSer;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGrabarCentroEvento;
    private javax.swing.JButton btGrabarServicio;
    private javax.swing.JComboBox cbDisponibleCentroEvento;
    private javax.swing.JTable grServicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCaracCentroEvento;
    private javax.swing.JLabel lbDisponibleCentroEvento;
    private javax.swing.JLabel lbHotelCentroEvento;
    private javax.swing.JLabel lbNombreServicio;
    private javax.swing.JLabel lbPrecioCentroEvento;
    private javax.swing.JLabel lbPrecioServicio;
    private javax.swing.JPanel panelCentroEventos;
    private javax.swing.JPanel panelServicios;
    private javax.swing.JTabbedPane tabContServicios;
    private javax.swing.JTextField txtCaracCentroEvento;
    private javax.swing.JTextField txtHotelCentroEvento;
    private javax.swing.JTextField txtNombreServicio;
    private javax.swing.JTextField txtPrecioCentroEvento;
    private javax.swing.JTextField txtPrecioServicio;
    // End of variables declaration//GEN-END:variables
}
