/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.hotel;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veranum.DAO.DAORegiones;
import veranum.DAO.DAOProvincia;
import veranum.DAO.DAOComuna;
import veranum.DAO.DAOHoteles;
import veranum.entities.ClHoteles;
import veranum.entities.ClProvincia;
import veranum.entities.ClRegion;

/**
 *
 * @author Duoc
 */
public class MainHotel extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainHotel
     */
    public MainHotel() {
        initComponents();
        //cbRegion.setModel(new DefaultComboBoxModel());
        for (Object item : DAORegiones.sqlLeerTodos()) {
            cbRegion.addItem(item);
        }
    }
    DefaultTableModel dt = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContenido = new javax.swing.JTabbedPane();
        panelHoteles = new javax.swing.JPanel();
        lbNombreHotel = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        cbRegion = new javax.swing.JComboBox();
        txtNombreHotel = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lbRegion = new javax.swing.JLabel();
        lbProvincia = new javax.swing.JLabel();
        lbComuna = new javax.swing.JLabel();
        cbProvincia = new javax.swing.JComboBox();
        cbComuna = new javax.swing.JComboBox();
        btGrabarHoteles = new javax.swing.JButton();
        lbCadena = new javax.swing.JLabel();
        txtCadena = new javax.swing.JTextField();
        panelHabitaciones = new javax.swing.JPanel();
        lbUbicacion = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        lbCantPersonas = new javax.swing.JLabel();
        txtCantPersonas = new javax.swing.JTextField();
        lbPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        lbCaracteristicas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCaracteristicas = new javax.swing.JTextArea();
        btGrabarHabitaciones = new javax.swing.JButton();
        panelMuebles = new javax.swing.JPanel();
        lbNombreMueble = new javax.swing.JLabel();
        txtNombreMueble = new javax.swing.JTextField();
        cbEstadoMueble = new javax.swing.JComboBox();
        lbEstadoMueble = new javax.swing.JLabel();
        btGrabarMuebles = new javax.swing.JButton();
        panelBuscarHab = new javax.swing.JPanel();
        lbBuscarHab = new javax.swing.JLabel();
        txtBuscarHab = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuscarHabitacion = new javax.swing.JTable();
        lbTipoBuscar = new javax.swing.JLabel();
        cbTipoBuscar = new javax.swing.JComboBox();
        btBuscarHabitacion = new javax.swing.JButton();
        panelBuscarHotel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaBuscarHotel = new javax.swing.JTable();
        lbNombreBuscarHotel = new javax.swing.JLabel();
        txtNombreBuscarHotel = new javax.swing.JTextField();
        btBuscarHotel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Hoteles"));
        setForeground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(557, 391));

        lbNombreHotel.setText("Nombre Hotel:");

        lbDireccion.setText("Dirección:");

        cbRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRegionItemStateChanged(evt);
            }
        });

        lbRegion.setText("Region:");

        lbProvincia.setText("Provincia:");

        lbComuna.setText("Comuna");

        cbProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProvinciaItemStateChanged(evt);
            }
        });

        btGrabarHoteles.setText("Grabar");
        btGrabarHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrabarHotelesActionPerformed(evt);
            }
        });

        lbCadena.setText("Cadena:");

        javax.swing.GroupLayout panelHotelesLayout = new javax.swing.GroupLayout(panelHoteles);
        panelHoteles.setLayout(panelHotelesLayout);
        panelHotelesLayout.setHorizontalGroup(
            panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotelesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHotelesLayout.createSequentialGroup()
                        .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDireccion)
                            .addComponent(lbRegion)
                            .addComponent(lbNombreHotel)
                            .addComponent(lbProvincia)
                            .addComponent(lbComuna))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(62, 62, 62))
                    .addGroup(panelHotelesLayout.createSequentialGroup()
                        .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHotelesLayout.createSequentialGroup()
                                .addComponent(lbCadena)
                                .addGap(61, 61, 61)
                                .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btGrabarHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 116, Short.MAX_VALUE))))
        );
        panelHotelesLayout.setVerticalGroup(
            panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotelesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreHotel)
                    .addComponent(txtNombreHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRegion)
                    .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProvincia)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComuna)
                    .addComponent(cbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadena)
                    .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btGrabarHoteles)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        tabContenido.addTab("Hoteles", panelHoteles);

        lbUbicacion.setText("Ubicación:");

        lbCantPersonas.setText("Cantidad de Personas:");

        lbPrecio.setText("Precio:");

        lbTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCaracteristicas.setText("Caracteristicas:");

        txtCaracteristicas.setColumns(20);
        txtCaracteristicas.setRows(5);
        jScrollPane1.setViewportView(txtCaracteristicas);

        btGrabarHabitaciones.setText("Grabar");

        javax.swing.GroupLayout panelHabitacionesLayout = new javax.swing.GroupLayout(panelHabitaciones);
        panelHabitaciones.setLayout(panelHabitacionesLayout);
        panelHabitacionesLayout.setHorizontalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHabitacionesLayout.createSequentialGroup()
                        .addComponent(lbUbicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHabitacionesLayout.createSequentialGroup()
                        .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPrecio)
                            .addComponent(lbTipo)
                            .addComponent(lbCaracteristicas)
                            .addComponent(lbCantPersonas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btGrabarHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHabitacionesLayout.setVerticalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantPersonas))
                .addGap(18, 18, 18)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCaracteristicas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGrabarHabitaciones)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tabContenido.addTab("Habitaciones", panelHabitaciones);

        lbNombreMueble.setText("Nombre Mueble:");

        cbEstadoMueble.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbEstadoMueble.setText("Estado Mueble:");

        btGrabarMuebles.setText("Grabar");

        javax.swing.GroupLayout panelMueblesLayout = new javax.swing.GroupLayout(panelMuebles);
        panelMuebles.setLayout(panelMueblesLayout);
        panelMueblesLayout.setHorizontalGroup(
            panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMueblesLayout.createSequentialGroup()
                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMueblesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreMueble)
                            .addComponent(lbEstadoMueble))
                        .addGap(62, 62, 62)
                        .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEstadoMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreMueble, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMueblesLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btGrabarMuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panelMueblesLayout.setVerticalGroup(
            panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMueblesLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombreMueble)
                    .addComponent(txtNombreMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstadoMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstadoMueble))
                .addGap(35, 35, 35)
                .addComponent(btGrabarMuebles)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        tabContenido.addTab("Muebles", panelMuebles);

        lbBuscarHab.setText("Habitación:");

        tableBuscarHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableBuscarHabitacion);

        lbTipoBuscar.setText("Tipo:");

        cbTipoBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btBuscarHabitacion.setText("Buscar");

        javax.swing.GroupLayout panelBuscarHabLayout = new javax.swing.GroupLayout(panelBuscarHab);
        panelBuscarHab.setLayout(panelBuscarHabLayout);
        panelBuscarHabLayout.setHorizontalGroup(
            panelBuscarHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarHabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelBuscarHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscarHabLayout.createSequentialGroup()
                        .addGroup(panelBuscarHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBuscarHab)
                            .addComponent(lbTipoBuscar))
                        .addGap(49, 49, 49)
                        .addGroup(panelBuscarHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarHabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBuscarHabitacion)
                .addGap(126, 126, 126))
        );
        panelBuscarHabLayout.setVerticalGroup(
            panelBuscarHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarHabLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelBuscarHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarHab)
                    .addComponent(txtBuscarHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btBuscarHabitacion)
                .addGap(1, 1, 1)
                .addGroup(panelBuscarHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoBuscar)
                    .addComponent(cbTipoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        tabContenido.addTab("Buscar habitación", panelBuscarHab);

        tablaBuscarHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaBuscarHotel);

        lbNombreBuscarHotel.setText("Nombre Hotel:");

        btBuscarHotel.setText("Buscar");
        btBuscarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarHotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarHotelLayout = new javax.swing.GroupLayout(panelBuscarHotel);
        panelBuscarHotel.setLayout(panelBuscarHotelLayout);
        panelBuscarHotelLayout.setHorizontalGroup(
            panelBuscarHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarHotelLayout.createSequentialGroup()
                .addGroup(panelBuscarHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarHotelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarHotelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbNombreBuscarHotel)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreBuscarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarHotel)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelBuscarHotelLayout.setVerticalGroup(
            panelBuscarHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarHotelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelBuscarHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreBuscarHotel)
                    .addComponent(txtNombreBuscarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarHotel))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tabContenido.addTab("Buscar Hotel", panelBuscarHotel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenido, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenido)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarProvincias(){
        int id_region = ((ClRegion)cbRegion.getSelectedItem()).getIdRegion();
        for (Object item : DAOProvincia.sqlPorRegion(id_region)) {
            cbProvincia.addItem(item);
        }
    }
    
    private void cargarComunas(){
        if(cbProvincia.getSelectedItem() != null) {
            int id_provincia = ((ClProvincia)cbProvincia.getSelectedItem()).getIdProvincia();
            for (Object item : DAOComuna.sqlPorProvincia(id_provincia)) {
                cbComuna.addItem(item);
            }
        }
    }
    private void cbRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRegionItemStateChanged
        // TODO add your handling code here:
        cbProvincia.removeAllItems();
        this.cargarProvincias();
        this.cargarComunas();
    }//GEN-LAST:event_cbRegionItemStateChanged

    private void cbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProvinciaItemStateChanged
        // TODO add your handling code here:
        cbComuna.removeAllItems();
        this.cargarComunas();
    }//GEN-LAST:event_cbProvinciaItemStateChanged

    private void btBuscarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarHotelActionPerformed
     
        ArrayList cli = DAOHoteles.sqlLeerTodos();
        dt =  (DefaultTableModel) tablaBuscarHotel.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }        
        for(int x=0; x < cli.size(); x++){
            ClHoteles xx = (ClHoteles)cli.get(x);
            Object[] fila = new Object[7];
            fila[0]= xx.getNombre();
            fila[1] = xx.getIdCadena();
            fila[2] = xx.getIdRegion();
            fila[3] = xx.getIdProvincia();
            fila[4] = xx.getIdComuna();
            fila[5] = xx.getDireccion();
            //fila[6] = xx.setIdHotel();                            
            dt.addRow(fila);             
         } 
    }//GEN-LAST:event_btBuscarHotelActionPerformed

    private void btGrabarHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrabarHotelesActionPerformed
        /*DAOHoteles.sqlInsert(new ClHoteles(Integer.parseInt(txtCadena.getText())
                                                            ,cbRegion.
                                                            ,cbProvincia
                                                            ,cbComuna
                                                            ,txtNombreHotel.getText()
                                                            ,txtDireccion.getText() )
                                );
        JOptionPane.showMessageDialog(this, "Agregado");
        */
    }//GEN-LAST:event_btGrabarHotelesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarHabitacion;
    private javax.swing.JButton btBuscarHotel;
    private javax.swing.JButton btGrabarHabitaciones;
    private javax.swing.JButton btGrabarHoteles;
    private javax.swing.JButton btGrabarMuebles;
    private javax.swing.JComboBox cbComuna;
    private javax.swing.JComboBox cbEstadoMueble;
    private javax.swing.JComboBox cbProvincia;
    private javax.swing.JComboBox cbRegion;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JComboBox cbTipoBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbBuscarHab;
    private javax.swing.JLabel lbCadena;
    private javax.swing.JLabel lbCantPersonas;
    private javax.swing.JLabel lbCaracteristicas;
    private javax.swing.JLabel lbComuna;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEstadoMueble;
    private javax.swing.JLabel lbNombreBuscarHotel;
    private javax.swing.JLabel lbNombreHotel;
    private javax.swing.JLabel lbNombreMueble;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbProvincia;
    private javax.swing.JLabel lbRegion;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTipoBuscar;
    private javax.swing.JLabel lbUbicacion;
    private javax.swing.JPanel panelBuscarHab;
    private javax.swing.JPanel panelBuscarHotel;
    private javax.swing.JPanel panelHabitaciones;
    private javax.swing.JPanel panelHoteles;
    private javax.swing.JPanel panelMuebles;
    private javax.swing.JTabbedPane tabContenido;
    private javax.swing.JTable tablaBuscarHotel;
    private javax.swing.JTable tableBuscarHabitacion;
    private javax.swing.JTextField txtBuscarHab;
    private javax.swing.JTextField txtCadena;
    private javax.swing.JTextField txtCantPersonas;
    private javax.swing.JTextArea txtCaracteristicas;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreBuscarHotel;
    private javax.swing.JTextField txtNombreHotel;
    private javax.swing.JTextField txtNombreMueble;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
