/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.hotel;

import helper.Formularios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veranum.DAO.DAOCadenas;
import veranum.DAO.DAORegiones;
import veranum.DAO.DAOProvincia;
import veranum.DAO.DAOComuna;
import veranum.DAO.DAOHoteles;
import veranum.entities.ClCadenas;
import veranum.entities.ClComuna;
import veranum.entities.ClHoteles;
import veranum.entities.ClProvincia;
import veranum.entities.ClRegion;

/**
 *
 * @author Duoc
 */
public class MainHotel extends javax.swing.JInternalFrame {

    private boolean paraGrabar = false;
    private DefaultTableModel dt = new DefaultTableModel();
    private int id_hotel = 0;
    /**
     * Creates new form MainHotel
     */
    public MainHotel() {
        initComponents();
        //cbRegion.setModel(new DefaultComboBoxModel());
        for (Object item : DAORegiones.sqlLeerTodos()) {
            cbRegion.addItem(item);
        }
        for (Object item : DAOCadenas.sqlLeerTodos()) {
            cbCadena.addItem(item);
        }
        
        grHotel.setEnabled(true);
        Formularios.DesactiveBotonesEliminarEditar(btEditarHotel, btEliminarHotel);
        btDesactivarEditarHotel.setVisible(false);
        this.leerTodos(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContenido = new javax.swing.JTabbedPane();
        panelHoteles = new javax.swing.JPanel();
        lbNombreHotel = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        cbRegion = new javax.swing.JComboBox();
        txtNombreHotel = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lbRegion = new javax.swing.JLabel();
        lbProvincia = new javax.swing.JLabel();
        lbComuna = new javax.swing.JLabel();
        cbProvincia = new javax.swing.JComboBox();
        cbComuna = new javax.swing.JComboBox();
        btGrabarHoteles = new javax.swing.JButton();
        lbCadena = new javax.swing.JLabel();
        cbCadena = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        grHotel = new javax.swing.JTable();
        btBuscarHotel = new javax.swing.JButton();
        btBuscarTodosHotel = new javax.swing.JButton();
        btEliminarHotel = new javax.swing.JButton();
        btEditarHotel = new javax.swing.JButton();
        txtBuscarHotel = new javax.swing.JTextField();
        btDesactivarEditarHotel = new javax.swing.JButton();
        panelHabitaciones = new javax.swing.JPanel();
        lbUbicacion = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        lbCantPersonas = new javax.swing.JLabel();
        txtCantPersonas = new javax.swing.JTextField();
        lbPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        lbCaracteristicas = new javax.swing.JLabel();
        btGrabarHabitaciones = new javax.swing.JButton();
        btEliminarHab = new javax.swing.JButton();
        btEditarHab = new javax.swing.JButton();
        txtBuscarHab = new javax.swing.JTextField();
        btBuscarHab = new javax.swing.JButton();
        btBuscarTodosHab = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        grHabitacion = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btDesactivarEditarHab = new javax.swing.JButton();
        panelTipoHab = new javax.swing.JPanel();
        btEliminarTipoHab = new javax.swing.JButton();
        btEditarTipoHab = new javax.swing.JButton();
        btBuscarTipoHab = new javax.swing.JButton();
        txtBuscarTipoHab = new javax.swing.JTextField();
        btBuscarTodoTipoHab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grTipoHab = new javax.swing.JTable();
        lbNombreTipoHab = new javax.swing.JLabel();
        txtNombreTipoHab = new javax.swing.JTextField();
        btGrabarTipoHab = new javax.swing.JButton();
        btDesactivarEditarTipoHab = new javax.swing.JButton();
        panelEstadoHab = new javax.swing.JPanel();
        btEliminarEstadoHab = new javax.swing.JButton();
        btEditarEstadoHab = new javax.swing.JButton();
        txtBuscarEstadoHab = new javax.swing.JTextField();
        btBuscarEstadoHab = new javax.swing.JButton();
        btBuscarTodosEstadoHab = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        grEstadoHab = new javax.swing.JTable();
        lbNombreEstadoHab = new javax.swing.JLabel();
        txtNombreEstadoHab = new javax.swing.JTextField();
        btGrabarEstadoHab = new javax.swing.JButton();
        btDesactivarEditarEstadoHab = new javax.swing.JButton();
        panelMuebles = new javax.swing.JPanel();
        lbNombreMueble = new javax.swing.JLabel();
        txtNombreMueble = new javax.swing.JTextField();
        cbEstadoMueble = new javax.swing.JComboBox();
        lbEstadoMueble = new javax.swing.JLabel();
        btGrabarMuebles = new javax.swing.JButton();
        btEliminarMueble = new javax.swing.JButton();
        btEditarMueble = new javax.swing.JButton();
        txtBuscarMueble = new javax.swing.JTextField();
        btBuscarMueble = new javax.swing.JButton();
        btBuscarTodosMueble = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        grMueble = new javax.swing.JTable();
        btDesactivarEditarMueble = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Hoteles"));
        setForeground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(557, 391));

        lbNombreHotel.setText("Nombre Hotel:");

        lbDireccion.setText("Dirección:");

        cbRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRegionItemStateChanged(evt);
            }
        });

        lbRegion.setText("Region:");

        lbProvincia.setText("Provincia:");

        lbComuna.setText("Comuna:");

        cbProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProvinciaItemStateChanged(evt);
            }
        });

        btGrabarHoteles.setText("Grabar");
        btGrabarHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrabarHotelesActionPerformed(evt);
            }
        });

        lbCadena.setText("Cadena:");

        grHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Cadena", "Nombre", "Region", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grHotelMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(grHotel);
        if (grHotel.getColumnModel().getColumnCount() > 0) {
            grHotel.getColumnModel().getColumn(0).setMaxWidth(30);
            grHotel.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        btBuscarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N
        btBuscarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarHotelActionPerformed(evt);
            }
        });

        btBuscarTodosHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N
        btBuscarTodosHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTodosHotelActionPerformed(evt);
            }
        });

        btEliminarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N
        btEliminarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarHotelActionPerformed(evt);
            }
        });

        btEditarHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N
        btEditarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarHotelActionPerformed(evt);
            }
        });

        btDesactivarEditarHotel.setBackground(new java.awt.Color(255, 0, 0));
        btDesactivarEditarHotel.setText("Salir Modo Editar");
        btDesactivarEditarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesactivarEditarHotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHotelesLayout = new javax.swing.GroupLayout(panelHoteles);
        panelHoteles.setLayout(panelHotelesLayout);
        panelHotelesLayout.setHorizontalGroup(
            panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotelesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbProvincia)
                    .addComponent(lbCadena)
                    .addGroup(panelHotelesLayout.createSequentialGroup()
                        .addComponent(lbDireccion)
                        .addGap(32, 32, 32)
                        .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHotelesLayout.createSequentialGroup()
                        .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRegion)
                            .addComponent(lbNombreHotel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHotelesLayout.createSequentialGroup()
                                .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbComuna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreHotel)))
                    .addComponent(btGrabarHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(panelHotelesLayout.createSequentialGroup()
                .addComponent(btEliminarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEditarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(txtBuscarHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarHotel)
                .addGap(3, 3, 3)
                .addComponent(btBuscarTodosHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHotelesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btDesactivarEditarHotel))
        );
        panelHotelesLayout.setVerticalGroup(
            panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHotelesLayout.createSequentialGroup()
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btEliminarHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscarHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditarHotel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarHotel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBuscarTodosHotel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDesactivarEditarHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreHotel)
                    .addComponent(txtNombreHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRegion)
                    .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProvincia)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbComuna)
                    .addComponent(cbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHotelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCadena)
                    .addComponent(cbCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGrabarHoteles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabContenido.addTab("Hoteles", panelHoteles);

        lbUbicacion.setText("Ubicación:");

        lbCantPersonas.setText("Cantidad de Personas:");

        lbPrecio.setText("Precio:");

        lbTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCaracteristicas.setText("Caracteristicas:");

        btGrabarHabitaciones.setText("Grabar");

        btEliminarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodosHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Ubicación", "Cant. Personas", "Precio", "Tipo", "Caracteristicas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(grHabitacion);
        if (grHabitacion.getColumnModel().getColumnCount() > 0) {
            grHabitacion.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btDesactivarEditarHab.setText("Salir Modo Editar");

        javax.swing.GroupLayout panelHabitacionesLayout = new javax.swing.GroupLayout(panelHabitaciones);
        panelHabitaciones.setLayout(panelHabitacionesLayout);
        panelHabitacionesLayout.setHorizontalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHabitacionesLayout.createSequentialGroup()
                        .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                                .addComponent(btEliminarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarHab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscarTodosHab))
                            .addComponent(btGrabarHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrecio)
                                    .addComponent(lbUbicacion)
                                    .addComponent(lbCantPersonas)
                                    .addComponent(lbTipo)
                                    .addComponent(lbCaracteristicas))
                                .addGap(26, 26, 26)
                                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelHabitacionesLayout.createSequentialGroup()
                                        .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addComponent(btDesactivarEditarHab))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelHabitacionesLayout.setVerticalGroup(
            panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarHab)
                    .addComponent(btEditarHab)
                    .addComponent(txtBuscarHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarHab)
                    .addComponent(btBuscarTodosHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUbicacion)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarHab))
                .addGap(18, 18, 18)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantPersonas)
                    .addComponent(txtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHabitacionesLayout.createSequentialGroup()
                        .addComponent(lbCaracteristicas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGrabarHabitaciones)
                .addContainerGap())
        );

        tabContenido.addTab("Habitaciones", panelHabitaciones);

        btEliminarTipoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarTipoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarTipoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodoTipoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grTipoHab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Nombre Tipo Habitación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grTipoHab);

        lbNombreTipoHab.setText("Nombre Tipo Habitación:");

        btGrabarTipoHab.setText("Grabar");

        btDesactivarEditarTipoHab.setText("Salir Modo Editar");

        javax.swing.GroupLayout panelTipoHabLayout = new javax.swing.GroupLayout(panelTipoHab);
        panelTipoHab.setLayout(panelTipoHabLayout);
        panelTipoHabLayout.setHorizontalGroup(
            panelTipoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoHabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoHabLayout.createSequentialGroup()
                        .addGroup(panelTipoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panelTipoHabLayout.createSequentialGroup()
                                .addComponent(btEliminarTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditarTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarTodoTipoHab)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelTipoHabLayout.createSequentialGroup()
                        .addGroup(panelTipoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btGrabarTipoHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTipoHabLayout.createSequentialGroup()
                                .addComponent(lbNombreTipoHab)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesactivarEditarTipoHab)
                        .addGap(91, 91, 91))))
        );
        panelTipoHabLayout.setVerticalGroup(
            panelTipoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoHabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarTipoHab)
                    .addComponent(btEditarTipoHab)
                    .addComponent(btBuscarTipoHab)
                    .addComponent(txtBuscarTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarTodoTipoHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelTipoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreTipoHab)
                    .addComponent(txtNombreTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarTipoHab))
                .addGap(18, 18, 18)
                .addComponent(btGrabarTipoHab)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        tabContenido.addTab("Tipo Habitación", panelTipoHab);

        btEliminarEstadoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarEstadoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarEstadoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodosEstadoHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grEstadoHab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Nombre Estado habitación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(grEstadoHab);

        lbNombreEstadoHab.setText("Nombre Estado Habitación:");

        btGrabarEstadoHab.setText("Grabar");

        btDesactivarEditarEstadoHab.setText("Salir Modo Editar");

        javax.swing.GroupLayout panelEstadoHabLayout = new javax.swing.GroupLayout(panelEstadoHab);
        panelEstadoHab.setLayout(panelEstadoHabLayout);
        panelEstadoHabLayout.setHorizontalGroup(
            panelEstadoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoHabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstadoHabLayout.createSequentialGroup()
                        .addGroup(panelEstadoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(panelEstadoHabLayout.createSequentialGroup()
                                .addComponent(btEliminarEstadoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditarEstadoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarEstadoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarEstadoHab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscarTodosEstadoHab)
                                .addGap(0, 66, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelEstadoHabLayout.createSequentialGroup()
                        .addGroup(panelEstadoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btGrabarEstadoHab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEstadoHabLayout.createSequentialGroup()
                                .addComponent(lbNombreEstadoHab)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreEstadoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesactivarEditarEstadoHab)
                        .addGap(47, 47, 47))))
        );
        panelEstadoHabLayout.setVerticalGroup(
            panelEstadoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoHabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarEstadoHab)
                    .addComponent(btEditarEstadoHab)
                    .addComponent(txtBuscarEstadoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarEstadoHab)
                    .addComponent(btBuscarTodosEstadoHab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelEstadoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreEstadoHab)
                    .addComponent(txtNombreEstadoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarEstadoHab))
                .addGap(18, 18, 18)
                .addComponent(btGrabarEstadoHab)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        tabContenido.addTab("Estado Habitación", panelEstadoHab);

        lbNombreMueble.setText("Nombre Mueble:");

        cbEstadoMueble.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbEstadoMueble.setText("Estado Mueble:");

        btGrabarMuebles.setText("Grabar");

        btEliminarMueble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N

        btEditarMueble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N

        btBuscarMueble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N

        btBuscarTodosMueble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N

        grMueble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Nombre Mueble", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(grMueble);
        if (grMueble.getColumnModel().getColumnCount() > 0) {
            grMueble.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btDesactivarEditarMueble.setText("Salir Modo Editar");

        javax.swing.GroupLayout panelMueblesLayout = new javax.swing.GroupLayout(panelMuebles);
        panelMuebles.setLayout(panelMueblesLayout);
        panelMueblesLayout.setHorizontalGroup(
            panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMueblesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(panelMueblesLayout.createSequentialGroup()
                        .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btGrabarMuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMueblesLayout.createSequentialGroup()
                                .addComponent(btEliminarMueble, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btEditarMueble, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarMueble, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarMueble)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscarTodosMueble))
                            .addGroup(panelMueblesLayout.createSequentialGroup()
                                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombreMueble)
                                    .addComponent(lbEstadoMueble))
                                .addGap(18, 18, 18)
                                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstadoMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelMueblesLayout.createSequentialGroup()
                                        .addComponent(txtNombreMueble, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btDesactivarEditarMueble)
                                        .addGap(27, 27, 27)))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMueblesLayout.setVerticalGroup(
            panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMueblesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarMueble)
                    .addComponent(btEditarMueble)
                    .addComponent(txtBuscarMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarMueble)
                    .addComponent(btBuscarTodosMueble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreMueble)
                    .addComponent(txtNombreMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarMueble))
                .addGap(18, 18, 18)
                .addGroup(panelMueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEstadoMueble)
                    .addComponent(cbEstadoMueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGrabarMuebles)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        tabContenido.addTab("Muebles", panelMuebles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenido, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenido)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDesactivarEditarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesactivarEditarHotelActionPerformed
        this.paraGrabar = false;
        this.btnEditarMode();
    }//GEN-LAST:event_btDesactivarEditarHotelActionPerformed

    private void btEditarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarHotelActionPerformed
        this.leerHotel(Formularios.getSelectedRow(grHotel));
        this.paraGrabar = true;
        this.btnEditarMode();
    }//GEN-LAST:event_btEditarHotelActionPerformed

    private void btEliminarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarHotelActionPerformed
        this.leerHotel(Formularios.getSelectedRow(grHotel));
        if(this.id_hotel == 0){
            JOptionPane.showMessageDialog(this, "NO existe para eliminar");
        }else{
            DAOHoteles.sqlDelete(new ClHoteles(this.id_hotel));
            JOptionPane.showMessageDialog(this, "Eliminado");
            helper.Formularios.limpiar(panelHoteles);
            Formularios.DesactiveBotonesEliminarEditar(btEditarHotel, btEliminarHotel);
            this.leerTodos(true);
        }
    }//GEN-LAST:event_btEliminarHotelActionPerformed

    private void btBuscarTodosHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTodosHotelActionPerformed
        this.leerTodos(true);
    }//GEN-LAST:event_btBuscarTodosHotelActionPerformed

    private void btBuscarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarHotelActionPerformed
        this.leerTodos(false);
    }//GEN-LAST:event_btBuscarHotelActionPerformed

    private void grHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grHotelMouseClicked
        int row_dos = Formularios.getTablaSeleccionada(evt, grHotel, 2);

        if(row_dos >= 0){
            this.leerHotel(Integer.parseInt(grHotel.getValueAt(row_dos, 0).toString()));
            Formularios.ActiveBotonesEliminarEditar(btEditarHotel, btEliminarHotel);
            this.paraGrabar = true;
            this.btnEditarMode();
        } else {
            Formularios.ActiveBotonesEliminarEditar(btEditarHotel, btEliminarHotel);
        }
    }//GEN-LAST:event_grHotelMouseClicked

    private void btGrabarHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrabarHotelesActionPerformed
        int id_cadena = ((ClCadenas)cbCadena.getSelectedItem()).getIdCadena();
        int id_region = ((ClRegion)cbRegion.getSelectedItem()).getIdRegion();
        int id_provi = ((ClProvincia)cbProvincia.getSelectedItem()).getIdProvincia();
        int id_comu = ((ClComuna)cbComuna.getSelectedItem()).getIdComuna();
        System.out.println(id_region);
        if(!paraGrabar){
            if(false ){ // validacion
            JOptionPane.showMessageDialog(this, "Ingrese los Datos");
            }else{
                DAOHoteles.sqlInsert(new ClHoteles( id_cadena, 
                                                    id_region, 
                                                    id_provi, 
                                                    id_comu, 
                                                    txtNombreHotel.getText(), 
                                                    txtDireccion.getText())
                                    );
                JOptionPane.showMessageDialog(this, "Agregado");
                Formularios.DesactiveBotonesEliminarEditar(btEditarHotel, btEliminarHotel);
                helper.Formularios.limpiar(panelHoteles);
                this.leerTodos(true);
            }  
        }else{
            DAOHoteles.sqlUpdate(new ClHoteles( this.id_hotel,
                                                id_cadena, 
                                                id_region, 
                                                id_provi, 
                                                id_comu, 
                                                txtNombreHotel.getText(), 
                                                txtDireccion.getText()));
            
            JOptionPane.showMessageDialog(this, "Modificado");
            Formularios.DesactiveBotonesEliminarEditar(btEditarHotel, btEliminarHotel);
            helper.Formularios.limpiar(panelHoteles);
            this.leerTodos(true);
            this.paraGrabar = false;
            this.btnEditarMode();
        }      
    }//GEN-LAST:event_btGrabarHotelesActionPerformed

    private void cbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProvinciaItemStateChanged
        // TODO add your handling code here:
        cbComuna.removeAllItems();
        this.cargarComunas();
    }//GEN-LAST:event_cbProvinciaItemStateChanged

    private void cbRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRegionItemStateChanged
        // TODO add your handling code here:
        cbProvincia.removeAllItems();
        this.cargarProvincias();
        this.cargarComunas();
    }//GEN-LAST:event_cbRegionItemStateChanged

    private void cargarProvincias(){
        int id_region = ((ClRegion)cbRegion.getSelectedItem()).getIdRegion();
        for (Object item : DAOProvincia.sqlPorRegion(id_region)) {
            cbProvincia.addItem(item);
        }
    }
    
    private void cargarComunas(){
        if(cbProvincia.getSelectedItem() != null) {
            int id_provincia = ((ClProvincia)cbProvincia.getSelectedItem()).getIdProvincia();
            for (Object item : DAOComuna.sqlPorProvincia(id_provincia)) {
                cbComuna.addItem(item);
            }
        }
    }
    // Method Custom
    private void leerHotel(int id){
        this.id_hotel = id;
        ClHoteles hotel = DAOHoteles.sqlLeer(id);
        txtNombreHotel.setText(hotel.getNombre());
        txtDireccion.setText(hotel.getDireccion());
        
        ClRegion reg;
        ClProvincia pro;
        ClComuna com;
        
        for (int i = 0; i < cbRegion.getItemCount(); i++)
        {
            reg = (ClRegion)cbRegion.getItemAt(i);
            if (reg.getIdRegion()== hotel.getIdRegion())
            {
                cbRegion.setSelectedIndex(i);
                break;
            }
        }
        
        for (int i = 0; i < cbProvincia.getItemCount(); i++)
        {
            pro = (ClProvincia)cbProvincia.getItemAt(i);
            if (pro.getIdProvincia()== hotel.getIdProvincia())
            {
                cbProvincia.setSelectedIndex(i);
                break;
            }
        }
        
        for (int i = 0; i < cbComuna.getItemCount(); i++)
        {
            com = (ClComuna)cbComuna.getItemAt(i);
            if (com.getIdComuna()== hotel.getIdComuna())
            {
                cbProvincia.setSelectedIndex(i);
                break;
            }
        }
        
    }
    
    private void leerTodos(boolean todos){
        ArrayList ser = new ArrayList<>();
        if(todos)
            ser = DAOHoteles.sqlLeerTodos();
        else 
            ser = DAOHoteles.sqlBuscarByNombre(txtBuscarHotel.getText());
        
        dt =  (DefaultTableModel) grHotel.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }        
        for(int x=0; x < ser.size(); x++){
            ClHoteles xx = (ClHoteles)ser.get(x);
            Object[] fila = new Object[7];
            fila[0] = xx.getIdHotel();
            fila[1] = ((ClCadenas)DAOCadenas.sqlLeer(xx.getIdCadena())).getNombre();
            fila[2] = xx.getNombre(); 
            fila[3] = ((ClRegion)DAORegiones.sqlLeer(xx.getIdRegion())).getNombre();
            fila[4] = xx.getDireccion(); 
            dt.addRow(fila);
        }
    }
    
    private void btnEditarMode(){
        if(!this.paraGrabar){
            btDesactivarEditarHotel.setVisible(false);
            helper.Formularios.limpiar(panelHoteles);
        } else {
            btDesactivarEditarHotel.setVisible(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarEstadoHab;
    private javax.swing.JButton btBuscarHab;
    private javax.swing.JButton btBuscarHotel;
    private javax.swing.JButton btBuscarMueble;
    private javax.swing.JButton btBuscarTipoHab;
    private javax.swing.JButton btBuscarTodoTipoHab;
    private javax.swing.JButton btBuscarTodosEstadoHab;
    private javax.swing.JButton btBuscarTodosHab;
    private javax.swing.JButton btBuscarTodosHotel;
    private javax.swing.JButton btBuscarTodosMueble;
    private javax.swing.JButton btDesactivarEditarEstadoHab;
    private javax.swing.JButton btDesactivarEditarHab;
    private javax.swing.JButton btDesactivarEditarHotel;
    private javax.swing.JButton btDesactivarEditarMueble;
    private javax.swing.JButton btDesactivarEditarTipoHab;
    private javax.swing.JButton btEditarEstadoHab;
    private javax.swing.JButton btEditarHab;
    private javax.swing.JButton btEditarHotel;
    private javax.swing.JButton btEditarMueble;
    private javax.swing.JButton btEditarTipoHab;
    private javax.swing.JButton btEliminarEstadoHab;
    private javax.swing.JButton btEliminarHab;
    private javax.swing.JButton btEliminarHotel;
    private javax.swing.JButton btEliminarMueble;
    private javax.swing.JButton btEliminarTipoHab;
    private javax.swing.JButton btGrabarEstadoHab;
    private javax.swing.JButton btGrabarHabitaciones;
    private javax.swing.JButton btGrabarHoteles;
    private javax.swing.JButton btGrabarMuebles;
    private javax.swing.JButton btGrabarTipoHab;
    private javax.swing.JComboBox cbCadena;
    private javax.swing.JComboBox cbComuna;
    private javax.swing.JComboBox cbEstadoMueble;
    private javax.swing.JComboBox cbProvincia;
    private javax.swing.JComboBox cbRegion;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JTable grEstadoHab;
    private javax.swing.JTable grHabitacion;
    private javax.swing.JTable grHotel;
    private javax.swing.JTable grMueble;
    private javax.swing.JTable grTipoHab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbCadena;
    private javax.swing.JLabel lbCantPersonas;
    private javax.swing.JLabel lbCaracteristicas;
    private javax.swing.JLabel lbComuna;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEstadoMueble;
    private javax.swing.JLabel lbNombreEstadoHab;
    private javax.swing.JLabel lbNombreHotel;
    private javax.swing.JLabel lbNombreMueble;
    private javax.swing.JLabel lbNombreTipoHab;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbProvincia;
    private javax.swing.JLabel lbRegion;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbUbicacion;
    private javax.swing.JPanel panelEstadoHab;
    private javax.swing.JPanel panelHabitaciones;
    private javax.swing.JPanel panelHoteles;
    private javax.swing.JPanel panelMuebles;
    private javax.swing.JPanel panelTipoHab;
    private javax.swing.JTabbedPane tabContenido;
    private javax.swing.JTextField txtBuscarEstadoHab;
    private javax.swing.JTextField txtBuscarHab;
    private javax.swing.JTextField txtBuscarHotel;
    private javax.swing.JTextField txtBuscarMueble;
    private javax.swing.JTextField txtBuscarTipoHab;
    private javax.swing.JTextField txtCantPersonas;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreEstadoHab;
    private javax.swing.JTextField txtNombreHotel;
    private javax.swing.JTextField txtNombreMueble;
    private javax.swing.JTextField txtNombreTipoHab;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
