/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.reservas;

import helper.Formularios;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import veranum.DAO.DAOEstadoHab;
import veranum.DAO.DAOHoteles;
import veranum.DAO.DAOReservar;
import veranum.DAO.DAOTipoHab;
import veranum.entities.ClHabitacionEstados;
import veranum.entities.ClHoteles;
import veranum.entities.ClPasajeros;
import veranum.entities.ClTipoHabitacion;
import veranum.entities.ClHabitaciones;

/**
 *
 * @author Duoc
 */
public class PasoDos_Reserva extends javax.swing.JPanel {
    private JTabbedPane myTab;
    private ClPasajeros pasajero;
    private DefaultTableModel dt = new DefaultTableModel();
    private Date date = new Date();
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private long dias = 0;

    /**
     * Creates new form PasoDos_Reserva
     * @param t
     * @param pasajero
     */
    public PasoDos_Reserva(JTabbedPane t, ClPasajeros pasajero) {
        initComponents();
        this.cargarHotel();
        this.cargarTipoHab();
        this.myTab = t;
        this.pasajero = pasajero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lbFechaIngreso = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JFormattedTextField(sdf.format(date));
        txtFechaSalida = new javax.swing.JFormattedTextField(sdf.format(date));
        lbFechaSalida = new javax.swing.JLabel();
        lblFechas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        grHabs = new javax.swing.JTable();
        lblHotel = new javax.swing.JLabel();
        cbHotel = new javax.swing.JComboBox();
        lblTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        lblCantPersonas = new javax.swing.JLabel();
        txtCantPersonas = new javax.swing.JTextField();
        btnBuscarHabitaciones = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblDias = new javax.swing.JLabel();

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/atras.png"))); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setText("Reservar Habitación");

        lbFechaIngreso.setText("Fecha Ingreso:");

        txtFechaIngreso.setFormatterFactory(new javax.swing.JFormattedTextField.AbstractFormatterFactory(){
            public javax.swing.JFormattedTextField.AbstractFormatter
            getFormatter(javax.swing.JFormattedTextField tf) {

                try {
                    javax.swing.text.MaskFormatter mf = new javax.swing.text.MaskFormatter("##/##/####");
                    mf.setPlaceholderCharacter('_');
                    return mf;
                } catch(java.text.ParseException pe){
                    pe.printStackTrace();
                }
                return null;
            }
        });
        txtFechaIngreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaIngresoFocusLost(evt);
            }
        });

        txtFechaSalida.setFormatterFactory(new javax.swing.JFormattedTextField.AbstractFormatterFactory(){
            public javax.swing.JFormattedTextField.AbstractFormatter
            getFormatter(javax.swing.JFormattedTextField tf) {

                try {
                    javax.swing.text.MaskFormatter mf = new javax.swing.text.MaskFormatter("##/##/####");
                    mf.setPlaceholderCharacter('_');
                    return mf;
                } catch(java.text.ParseException pe){
                    pe.printStackTrace();
                }
                return null;
            }
        });
        txtFechaSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaSalidaFocusLost(evt);
            }
        });

        lbFechaSalida.setText("Fecha Salida:");

        lblFechas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblFechas.setText("Fechas de reserva: ");

        grHabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Ubicación", "Cant. Personas", "Precio", "Tipo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grHabs);

        lblHotel.setText("Hotel: ");

        lblTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas" }));

        lblCantPersonas.setText("Cant. Personas:");

        btnBuscarHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N
        btnBuscarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHabitacionesActionPerformed(evt);
            }
        });

        lblDias.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbFechaIngreso)
                                        .addGap(43, 43, 43)
                                        .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbFechaSalida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblFechas))
                            .addComponent(lblTitulo)))
                    .addComponent(btnAtras))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHotel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCantPersonas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblDias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblFechas)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaIngreso)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaSalida)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCantPersonas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHotel)
                                .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTipo)
                                .addComponent(lblCantPersonas))
                            .addComponent(cbTipo, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(btnBuscarHabitaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        myTab.setEnabledAt(1, false);
        myTab.setSelectedIndex(0);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtFechaIngresoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaIngresoFocusLost
        Formularios.deStringAFecha(txtFechaIngreso.getText());
    }//GEN-LAST:event_txtFechaIngresoFocusLost

    private void txtFechaSalidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaSalidaFocusLost
        Formularios.deStringAFecha(txtFechaSalida.getText());
        this.calcularDias();
    }//GEN-LAST:event_txtFechaSalidaFocusLost

    private void btnBuscarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHabitacionesActionPerformed
        this.leerBuscar();
    }//GEN-LAST:event_btnBuscarHabitacionesActionPerformed

    private void calcularDias()
    {
        this.dias = Formularios.diasBetweenFechas(txtFechaIngreso.getText(), txtFechaSalida.getText());
        if(this.dias <= 0){
            JOptionPane.showMessageDialog(this, "La fecha de salida tiene que ser superior a la de entrada. ");
        }
    }
    private void leerBuscar()
    {
        ArrayList rol = new ArrayList<>();
        int cant = 0;
        int tipo = 0;
        
        if(!txtCantPersonas.getText().equals("")){
            cant = Integer.parseInt(txtCantPersonas.getText());
        }
        
        if(cbTipo.getSelectedItem() != "Todas")
            tipo = ((ClTipoHabitacion)cbTipo.getSelectedItem()).getIdTipoHabit();
        
        try {
            rol = DAOReservar.sqlBuscarHabitacion(
                    ((ClHoteles)cbHotel.getSelectedItem()).getIdHotel(),
                    tipo,
                    cant
            );
        } catch (SQLException ex) {
            Logger.getLogger(PasoDos_Reserva.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dt =  (DefaultTableModel) grHabs.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }        
        for(int x=0; x < rol.size(); x++){
            ClHabitaciones xx = (ClHabitaciones)rol.get(x);
            Object[] fila = new Object[7];
            fila[0] = xx.getIdHabitacion();
            fila[1] = xx.getUbicacion();
            fila[2] = xx.getCantPersonas();
            fila[3] = xx.getPrecio();
            fila[4] = ((ClTipoHabitacion)DAOTipoHab.sqlLeer(xx.getIdHabitacionTipo())).getNombre();
            fila[5] = ((ClHabitacionEstados)DAOEstadoHab.sqlLeer(xx.getIdHabitacionEstado())).getEstado();
            dt.addRow(fila);
        }
    }
    private void cargarHotel(){
        for (Object dato : DAOHoteles.sqlLeerTodos()) {
            cbHotel.addItem(dato);
        }
    }
    
    private void cargarTipoHab(){
        for (Object dato : DAOTipoHab.sqlLeerTodos()) {
            cbTipo.addItem(dato);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarHabitaciones;
    private javax.swing.JComboBox cbHotel;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JTable grHabs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbFechaIngreso;
    private javax.swing.JLabel lbFechaSalida;
    private javax.swing.JLabel lblCantPersonas;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblFechas;
    private javax.swing.JLabel lblHotel;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCantPersonas;
    private javax.swing.JFormattedTextField txtFechaIngreso;
    private javax.swing.JFormattedTextField txtFechaSalida;
    // End of variables declaration//GEN-END:variables
}
