/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.reservas;

import helper.Formularios;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import veranum.DAO.DAOReservar;
import veranum.entities.ClHabitaciones;
import veranum.entities.ClReservar;

/**
 *
 * @author carlosdlg
 */
public class PasoCuatro_Finalizar extends javax.swing.JPanel {
    private final JTabbedPane myTab;
    private final ClReservar reserva;
    private String detalle = "";
    /**
     * Creates new form PasoCuatro_Finalizar
     * @param t
     * @param reserva
     */
    public PasoCuatro_Finalizar(JTabbedPane t, ClReservar reserva) {
        initComponents();
        this.myTab = t;
        this.reserva = reserva;
        
        try {
            DAOReservar.sqlInsert(this.reserva);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error a Insertar los datos");
        }
    }

    public String generarDetalle(){
        detalle += "\n---------------------------------------------\n";
        detalle += "Nombre: "+reserva.getUsuario().getNombre();
        detalle += " "+reserva.getUsuario().getApellido_pa();
        detalle += " "+reserva.getUsuario().getApellido_ma();
        detalle += "\n";
        detalle += "Rut: "+reserva.getUsuario().getRut();
        detalle += "\n";
        detalle += "Fecha Ingreso: "+Formularios.deFechaToString(reserva.getFechaIngreso());
        detalle += "\n";
        detalle += "Fecha Salida: "+Formularios.deFechaToString(reserva.getFechaSalida());
        detalle += "\n---------------------------------------------\n";
        detalle += "-- Habitaciones: ";
        detalle += "\n---------------------------------------------\n";
        
        for(int i = 0; i < reserva.getReservas().size(); i++){
            ClHabitaciones xx = (ClHabitaciones)reserva.getReservas().get(i);
            detalle += "#"+i;
            detalle += "| ";
            detalle += "\n";
        }
        return this.detalle;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDetalle = new javax.swing.JLabel();

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblTitulo.setText("¡Reserva Finalizada!");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hotel Veranum Detalle de Reserva");

        lblDetalle.setText("DETALLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblDetalle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetalle)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
